### ISSUE TITLE
Command line usage

### ISSUE THREAD

**Issue by toboid** [JoshWillik/json-expand#2]
When installed using `npm install -g json-expand` this module cannot be used from the command line. I'd be happy to look at this if you can add an appropriate license to the project as per #1

**Comment by JoshWillik** [comment]
@toboid I have #1 patched up. If you wanted to add global runability, I'll accept the PR

**Comment by JoshWillik** [comment]
Thanks for your help

**Comment by toboid** [comment]
No worries
